name: Daily Weather

on:
  schedule:
    - cron: "0 15 * * *"  # 毎日UTC 15:00 → JST 翌00:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir openai==0.28.1
          pip install --no-cache-dir -r requirements.txt

      - name: Run bot
        run: python weather_line_bot.py
        env:
          WEATHER_API_KEY:   ${{ secrets.WEATHER_API_KEY }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID:      ${{ secrets.LINE_USER_ID }}
